local_backend: true

backend:
  name: git-gateway
  repo: "affilirator/bestofvacuum" # Replace with your GitHub username and repository name
  branch: local.dev


site_url: https://bestofvacuum.com
display_url: bestofvacuum.com
logo_url: https://www.bestofvacuum.com/images/logo.svg
show_preview_links: true
publish_mode: editorial_workflow
media_folder: "src/content/blog/images"
public_folder: "src/content/blog/images"

collections:

  - name: "legalpages"
    label: "Legal Pages"
    publish: false
    files:
      - name: "privacy_policy"
        label: "Privacy Policy"
        file: "src/content/legal/privacy-policy.md"
        fields:
          - { name: "title", label: "Page Title", widget: "string" }
          - { name: "last_updated", label: "Last Updated", widget: "datetime" }
          - name: "sections"
            label: "Policy Sections"
            widget: "list"
            fields:
              - { name: "id", label: "Section ID", widget: "string", description: "Unique identifier for the section" }
              - { name: "title", label: "Section Title", widget: "string" }
              - { name: "content", label: "Content", widget: "markdown" }
          - name: "contact"
            label: "Contact Information"
            widget: "object"
            fields:
              - { name: "email", label: "Contact Email", widget: "string" }
              - { name: "address", label: "Mailing Address", widget: "text" }
  - name: "categories"
    label: "Categories"
    folder: "src/content/categories"
    identifier_field: "slug"
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }

  - name: "authors"
    label: "Authors"
    folder: "src/content/authors"
    identifier_field: "slug"
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Full Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - {
          label: "Profile Image",
          name: "image",
          widget: "image",
          media_folder: "/public/images/authors",
          public_folder: "/images/authors"
        }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string" }
  - name: "posts"
    label: "Blog Posts 2"
    folder: "src/content/posts"
    create: true
    slug: "{{originalUrl}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Author, name: author, widget: string }
      - { label: "Author Bio", name: authorBio, widget: text }
      - {
          label: "Author Image",
          name: authorImage,
          widget: image,
          media_folder: "/public/images/authors",
          public_folder: "/images/authors"
        }
      - { label: "Author Image Alt Text", name: authorImageAlt, widget: string }
      - {
          label: "Show Table of Contents",
          name: showTableOfContents,
          widget: boolean,
          default: true
        }
      - { label: "Featured Image", name: image, widget: image }
      - { label: "Cover Alt Text", name: coverAlt, widget: string }
      - {
          label: "Publish Date",
          name: pubDate,
          widget: datetime,
          format: "YYYY-MM-DD",
          date_format: "YYYY-MM-DD",
          time_format: false
        }
      - {
          label: "Modified Date",
          name: modDate,
          widget: datetime,
          format: "YYYY-MM-DD",
          date_format: "YYYY-MM-DD",
          time_format: false
        }
      - { label: "URL Slug", name: originalUrl, widget: string }
      - {
          label: Category,
          name: category,
          widget: select,
          options: ["Vacuum Reviews", "Cleaning Tips", "Product Guides"]
        }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Body, name: body, widget: markdown }


  - name: "blog"
    label: "WordPress Posts"
    preview_path: "/blog/{{slug}}/"
    folder: "src/content/blog"
    filter: { field: "source", value: "wordpress" }
    description: "Blog posts and articles fetched from Wordpress. No additionals can be made here."
    create: false
    slug: "{{originalUrl}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "hidden", default: "{{fields.pubDate}}" }
      - { label: "Source", name: "source", widget: "string", default: "wordpress" }
      - {label: "URL Slug", name: "originalUrl", widget: "string"}
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogLayout.astro" }
      - {label: "Publication Date", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, }
      - {label: "Modified Date", name: "modDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "excerpt", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Show Table of Contents", name: "showTableOfContents", widget: "boolean", default: true}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Bio", name: "authorBio", widget: "text"}
      - {label: "Author Image", name: "authorImage", widget: "image", required: false}
      - {label: "Author Image Alt Text", name: "authorImageAlt", widget: "string", required: false}
      - {label: "Cover Alt Text", name: "coverAlt", widget: "string", required: false}

  - name: "cmsblog"
    label: "CMS Posts"
    preview_path: "/blog/{{slug}}/"
    folder: "src/content/blog"
    filter: { field: "source", value: "decap" }
    description: "Blog posts and articles fetched from Wordpress. No additionals can be made here."
    create: true
    slug: "{{originalUrl}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "hidden", default: "{{fields.pubDate}}" }
      - { label: "Source", name: "source", widget: "string", default: "decap" }
      - {label: "URL Slug", name: "originalUrl", widget: "string"}
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogLayout.astro" }
      - {label: "Publication Date", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, }
      - {label: "Modified Date", name: "modDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "excerpt", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Show Table of Contents", name: "showTableOfContents", widget: "boolean", default: true}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Bio", name: "authorBio", widget: "text"}
      - {label: "Author Image", name: "authorImage", widget: "image", required: false}
      - {label: "Author Image Alt Text", name: "authorImageAlt", widget: "string", required: false}
      - {label: "Cover Alt Text", name: "coverAlt", widget: "string", required: false}


  - name: "reviews"
    label: "Vacuum Reviews"
    folder: "src/content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publication Date", name: "pubDate", widget: "datetime"}
      - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5, step: 0.1}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Brand", name: "brand", widget: "string"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Upright", "Stick", "Robot", "Canister", "Handheld", "Wet/Dry", "Commercial"]}
      - {label: "Price", name: "price", widget: "number", required: false}
      - {label: "Pros", name: "pros", widget: "list"}
      - {label: "Cons", name: "cons", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "team"
    label: "Team Members"
    folder: "src/content/team"
    create: true
    slug: "{{fields.name | slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Credentials", name: "credentials", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false, default: "/images/placeholder.svg"}
      - {label: "Expertise", name: "expertise", widget: "list"}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Founded Year", name: "foundedYear", widget: "number"}
          - {label: "Content", name: "body", widget: "markdown"}

      - file: "src/content/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Office Hours", name: "officeHours", widget: "list", fields: [
              {label: "Day", name: "day", widget: "string"},
              {label: "Hours", name: "hours", widget: "string"}
            ]}
